apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qsjyw645j-nodejs
  janus-idp.io/tekton: qsjyw645j-nodejs
  backstage.io/kubernetes-id: qsjyw645j-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qsjyw645j-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
